### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nikosalonen** [TheBastionBot/BastionBotDocs#11]
On the "Get started" page the arrow link which is supposed to link to the "Get API Keys" page is broken. 

https://docs.bastionbot.org/get-started

Instead of opening url /get-api-keys it /get-started/api-keys/

**Comment by k3rn31p4nic** [comment]
Fixed in https://github.com/TheBastionBot/BastionBotDocs/commit/91b8dd44d22f2f8cff21d3bb10718ed3f400b153
